# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autoTM.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(290, 225)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 271, 181))
        self.widget.setObjectName("widget")
        self.lineEdit1 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit1.setGeometry(QtCore.QRect(10, 30, 156, 23))
        self.lineEdit1.setMinimumSize(QtCore.QSize(0, 23))
        self.lineEdit1.setObjectName("lineEdit1")
        self.lineEdit2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit2.setGeometry(QtCore.QRect(10, 60, 156, 23))
        self.lineEdit2.setMinimumSize(QtCore.QSize(0, 23))
        self.lineEdit2.setObjectName("lineEdit2")
        self.lineEdit3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit3.setGeometry(QtCore.QRect(10, 90, 156, 23))
        self.lineEdit3.setMinimumSize(QtCore.QSize(0, 23))
        self.lineEdit3.setObjectName("lineEdit3")
        self.lineEdit4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit4.setGeometry(QtCore.QRect(10, 120, 156, 23))
        self.lineEdit4.setMinimumSize(QtCore.QSize(0, 23))
        self.lineEdit4.setObjectName("lineEdit4")
        self.lineEdit5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit5.setGeometry(QtCore.QRect(10, 150, 156, 23))
        self.lineEdit5.setMinimumSize(QtCore.QSize(0, 23))
        self.lineEdit5.setObjectName("lineEdit5")
        self.startBtn1 = QtWidgets.QPushButton(self.widget)
        self.startBtn1.setGeometry(QtCore.QRect(170, 30, 75, 23))
        self.startBtn1.setObjectName("startBtn1")
        self.startBtn2 = QtWidgets.QPushButton(self.widget)
        self.startBtn2.setGeometry(QtCore.QRect(170, 60, 75, 23))
        self.startBtn2.setObjectName("startBtn2")
        self.startBtn3 = QtWidgets.QPushButton(self.widget)
        self.startBtn3.setGeometry(QtCore.QRect(170, 90, 75, 23))
        self.startBtn3.setObjectName("startBtn3")
        self.startBtn4 = QtWidgets.QPushButton(self.widget)
        self.startBtn4.setGeometry(QtCore.QRect(170, 120, 75, 23))
        self.startBtn4.setObjectName("startBtn4")
        self.startBtn5 = QtWidgets.QPushButton(self.widget)
        self.startBtn5.setGeometry(QtCore.QRect(170, 150, 75, 23))
        self.startBtn5.setObjectName("startBtn5")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 0, 156, 20))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 290, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "auto"))
        self.startBtn1.setText(_translate("MainWindow", "start"))
        self.startBtn2.setText(_translate("MainWindow", "start"))
        self.startBtn3.setText(_translate("MainWindow", "start"))
        self.startBtn4.setText(_translate("MainWindow", "start"))
        self.startBtn5.setText(_translate("MainWindow", "start"))
        self.label.setText(_translate("MainWindow", "window title"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
